// Existing DUMMY_COURSES array
export const DUMMY_COURSES = [
  {
    $id: '1',
    title: 'PG Diploma in Clinical Cosmetology',
    description: 'Master the art of Botox injections with our comprehensive course covering facial anatomy, injection techniques, and patient safety.',
    price: 299,
    originalPrice: 1699,
    categoryId: '1',
    duration: '8 hours',
    thumbnail: require('@/assets/images/one.png'),
    status: 'published',
    enrolledCount: 150,
    rating: 5.0,
    instructor: 'Essar Team',
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    $id: '2',
    title: 'Fellowship in Cosmetology Laser & Facial Aesthetics',
    description: 'Learn advanced dermal filler techniques including lip augmentation, cheek enhancement, and under-eye treatments.',
    price: 349,
    originalPrice: 1899,
    categoryId: '1',
    duration: '10 hours',
    thumbnail: require('@/assets/images/two.png'),
    status: 'published',
    enrolledCount: 120,
    rating: 4.8,
    instructor: 'Essar Team',
    createdAt: '2024-01-02T00:00:00.000Z',
  },
  {
    $id: '3',
    title: 'Certificate in Laser Therapy',
    description: 'Complete training on laser hair removal procedures, safety protocols, and client consultation.',
    price: 449,
    originalPrice: 2499,
    categoryId: '2',
    duration: '12 hours',
    thumbnail: require('@/assets/images/three.png'),
    status: 'published',
    enrolledCount: 85,
    rating: 4.9,
    instructor: 'Essar Team',
    createdAt: '2024-01-03T00:00:00.000Z',
  },
  {
    $id: '4',
    title: 'Master Course in Trichology',
    description: 'Learn to perform comprehensive skin analysis and create personalized treatment plans.',
    price: 199,
    originalPrice: 999,
    categoryId: '3',
    duration: '6 hours',
    thumbnail: require('@/assets/images/for.png'),
    status: 'published',
    enrolledCount: 200,
    rating: 4.7,
    instructor: 'Essar Team',
    createdAt: '2024-01-04T00:00:00.000Z',
  },
  {
    $id: '5',
    title: 'Fellowship in Aesthetic Science',
    description: 'Learn to perform comprehensive skin analysis and create personalized treatment plans.',
    price: 399,
    originalPrice: 1999,
    categoryId: '3',
    duration: '6 hours',
    thumbnail: require('@/assets/images/five.png'),
    status: 'published',
    enrolledCount: 200,
    rating: 5.0,
    instructor: 'Essar Team',
    createdAt: '2024-01-04T00:00:00.000Z',
  },
  {
    $id: '6',
    title: 'Hijama/Cupping & Leech Therapy',
    description: 'Learn to perform comprehensive skin analysis and create personalized treatment plans.',
    price: 299,
    originalPrice: 1499,
    categoryId: '3',
    duration: '6 hours',
    thumbnail: require('@/assets/images/six.png'),
    status: 'published',
    enrolledCount: 200,
    rating: 4.6,
    instructor: 'Essar Team',
    createdAt: '2024-01-04T00:00:00.000Z',
  },
  {
    $id: '7',
    title: 'PG Diploma in Diet & Nutrition',
    description: 'Learn to perform comprehensive skin analysis and create personalized treatment plans.',
    price: 199,
    originalPrice: 1099,
    categoryId: '3',
    duration: '6 hours',
    thumbnail: require('@/assets/images/seven.png'),
    status: 'published',
    enrolledCount: 200,
    rating: 4.8,
    instructor: 'Essar Team',
    createdAt: '2024-01-04T00:00:00.000Z',
  },
];

// Detail page ke liye - simple!
export const getDummyCourseDetails = (courseId) => {
  return DUMMY_COURSES.find(course => course.$id === courseId) || null;
};

// Course contents - bus 3-4 lessons
export const getDummyCourseContents = (courseId) => {
  return [
    {
      $id: `${courseId}-1`,
      courseId: courseId,
      title: 'Introduction & Overview',
      type: 'video',
      duration: '45 min',
      url: 'https://example.com/video1',
      order: 1,
      createdAt: '2024-01-01T00:00:00.000Z',
    },
    {
      $id: `${courseId}-2`,
      courseId: courseId,
      title: 'Core Concepts & Techniques',
      type: 'video',
      duration: '60 min',
      url: 'https://example.com/video2',
      order: 2,
      createdAt: '2024-01-01T00:00:00.000Z',
    },
    {
      $id: `${courseId}-3`,
      courseId: courseId,
      title: 'Practical Applications',
      type: 'video',
      duration: '55 min',
      url: 'https://example.com/video3',
      order: 3,
      createdAt: '2024-01-01T00:00:00.000Z',
    },
    {
      $id: `${courseId}-4`,
      courseId: courseId,
      title: 'Final Assessment',
      type: 'document',
      duration: '30 min',
      url: 'https://example.com/assessment',
      order: 4,
      createdAt: '2024-01-01T00:00:00.000Z',
    },
  ];
};
